apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 9092
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: 2181
        - name: ZOOKEEPER_TICK_TIME
          value: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
  - port: 9092
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: 1
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - port: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dio-waiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dio-waiter
  template:
    metadata:
      labels:
        app: dio-waiter
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: dio-waiter
        image: felipetomino/dio-waiter:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: 3000
        - name: KAFKA_BROKER_URI
          value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: dio-waiter
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: dio-waiter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dio-cooker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dio-cooker
  template:
    metadata:
      labels:
        app: dio-cooker
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: dio-cooker
        image: felipetomino/dio-kitchen:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 3000
        env:
        - name: CONSUMER_TYPE
          value: Cooker
        - name: KAFKA_BROKER_URI
          value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: dio-cooker
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: dio-cooker
---
apiVersion: v1
kind: Service
metadata:
  name: dio-waiter
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: dio-waiter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dio-bartender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dio-bartender
  template:
    metadata:
      labels:
        app: dio-bartender
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: dio-bartender
        image: felipetomino/dio-kitchen:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 3000
        env:
        - name: CONSUMER_TYPE
          value: Bartender
        - name: KAFKA_BROKER_URI
          value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: dio-bartender
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: dio-bartender